server:
  port: 8993
spring:
  application:
    name: order-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8752/eureka
mybatis:
  mapper-locations: classpath*:mybats/*Mapper.xml
  type-aliases-package: com.jk.yyb.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
