server:
  port: 8681
spring:
  application:
    name: order-web
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8752/eureka
